### ISSUE TITLE
BeginContainter throwing an InvalidOperationException

### ISSUE THREAD

**Issue by BoredNumb** [empira/PDFsharp-samples#3]
Application set up in .NET 8.0.

PDFsharp-MigraDoc-GDI (version 6.1.1) loaded from NuGet

Code copied from repository.

Debug runs up until the line "XGraphicsContainer container = gfx.BeginContainer(rect, A4Rect, XGraphicsUnit.Point);" in the SamplePage2 method in when it throws the exception.

rect defined as:
(9.9212598425, 14.031496063, 178.5826771654, 252.5669291339)

A4Rect defined as:
(0, 0, 595.2755905512, 841.8897637795)

**Comment by ThomasHoevel** [comment]
There is no call to `BeginContainer` in the old PDFsharp samples, is there?

**Comment by ThomasHoevel** [comment]
Fixed with PDFsharp 6.2.0 Preview 2.
Cannot yet say when it will be published.
